Item(by='phoe-krk', descendants=None, kids=None, score=None, time=1603485958, title=None, item_type='comment', url=None, parent=24873859, text='Yes, I&#x27;m implying that. For instance, a lot of Python&#x27;s use of &quot;throw&quot; is not really because we want to signal an exception in some Python code, we just want to unwind the stack while passing some values and we can&#x27;t do it in any other way in the language.<p>Again, that&#x27;s just control flow, and that&#x27;s because throwing exceptions is the only way of performing non-local exits in those languages. Actual exception handling starts when the existing control flow cannot handle some situation that has occurred, and someone - or something - needs to be able to create new control flow dynamically in order to continue program execution and therefore the process that was ongoing there.<p>Or, you know, we can do the industry standard: crash the program, and restart the thread or daemon or virtual machine or server cluster in question in hope that turning it off and on again helps. &#x2F;s')