Item(by='derriz', descendants=None, kids=None, score=None, time=1606774590, title=None, item_type='comment', url=None, parent=25255276, text='With checked exceptions it&#x27;s not clear how control can pass into the catch block (using Java terminology).  The fact that a method can throw a particular exception is not visible at the call site so unless you examine the declaration or definition of every method call within the try block, you cannot be sure from where control can jump to the catch block.<p>And if there are multiple places within the try block where the caught checked exception can be thrown, then basically the catch block can do nothing sensible with respect to recovery or even guaranteeing anything about the current state of the world once you&#x27;re in the catch block.<p>I&#x27;ve seen some horribly ugly patterns used in an attempt to deal with this - basically you need to explicitly record progress within the try block which can be tested in the catch block.<p>And whatever about Java - at least the design decision hasn&#x27;t completely poisoned the subsequent development of the language.  Whenever I use C++, it feels like a massive amount of the complexity, wizardry and arcane&#x2F;complex patterns required to write &quot;safe&quot; C++ would not be necessary if they hadn&#x27;t added exceptions to the language early on.')