Item(by='oprypin', descendants=None, kids=None, score=None, time=1607594436, title=None, item_type='comment', url=None, parent=25371878, text='Same. But for me there has been one particular recurring kind of breakage. Python version upgrades (most recently 3.8 -&gt; 3.9) invalidate all manually installed packages and virtualenvs. Mitigated by using Arch packages for Python packages instead...')