Item(by='dmurray', descendants=None, kids=None, score=None, time=1610105688, title=None, item_type='comment', url=None, parent=25654955, text='I thought I spotted a bug on the very first day, part 2.<p><pre><code>  def day1_2(nums):\n    &quot;Find 3 distinct numbers that sum to 2020, and return their product.&quot;\n    return first(x * y * z \n                 for x, y in combinations(nums, 2) \n                 for z in nums &amp; {2020 - x - y} \n                 if x != z != y)\n</code></pre>\nThe last line (if x != z != y) returns true when x and y are equal and z is different.<p>But x and y are already constrained to be different since nums is a set and itertools combinations picks distinct elements from the iterable. If the test had been x != y != z it would have been a bug.')