Item(by='nathan815', descendants=None, kids=None, score=None, time=1610401175, title=None, item_type='comment', url=None, parent=25728374, text='&gt; the error could also be more obvious and the code just fails open. someone has a try&#x2F;catch and returns true either because of an accidental mistake or because they don&#x27;t want users to be locked out when the provider is down.<p>Failing open would be a catastrophic mistake either way. &quot;The auth provider is down, just let everyone in!&quot;')