Item(by='9wzYQbTYsAIc', descendants=15, kids=[25818574, 25805432, 25818027, 25805208, 25806564], score=23, time=1610828889, title='Python infrastructure DDoS ongoing', item_type='story', url='https://status.python.org/', parent=None, text=None)