Item(by='9wzYQbTYsAIc', descendants=13, kids=[25805432, 25805208, 25806564], score=23, time=1610828889, title='Python infrastructure DDoS ongoing', item_type='story', url='https://status.python.org/', parent=None, text=None)