Item(by='groodt', descendants=660, kids=[25889412, 25888991, 25889328, 25890486, 25891639, 25890545, 25891818, 25892625, 25889025, 25888803, 25888452, 25892418, 25888819, 25889049, 25888897, 25894402, 25888463, 25889462, 25894946, 25893434, 25889455, 25889807, 25891028, 25890582, 25888552, 25890901, 25891880, 25888925, 25889170, 25892119, 25890237, 25888475, 25892432, 25891634, 25889901, 25888658, 25888511, 25890523, 25888730], score=763, time=1611453703, title='Pip has dropped support for Python 2', item_type='story', url='https://pip.pypa.io/en/stable/news/#id1', parent=None, text=None)