Item(by='groodt', descendants=454, kids=[25889412, 25888991, 25889328, 25891639, 25890486, 25892418, 25891818, 25890545, 25888452, 25888803, 25889025, 25891880, 25889049, 25890582, 25892432, 25888819, 25888463, 25891028, 25892119, 25888897, 25890901, 25889455, 25888658, 25889462, 25888552, 25891634, 25889807, 25888925, 25889170, 25890237, 25888475, 25889901, 25888511, 25890523, 25888730], score=601, time=1611453703, title='Pip has dropped support for Python 2', item_type='story', url='https://pip.pypa.io/en/stable/news/#id1', parent=None, text=None)